Parameters:
  # Paramenters are entirely optional.
  # but using them will make your cloudformation templates more reusable
  # use them for things that may change over time, such as instance type,
  # VPCs and so on.
  UdaVPC:
    Type: String
    Description: Name of the App
    Default: "saa-ha-app-VPCID"

Resources:
  # IAM
  UdacityS3ReadOnlyEC2:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: UdacityS3ReadOnlyEC2
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      RoleName: UdacityS3ReadOnlyEC2
      Tags: 
        - Key: course-work
          Value: true
        - Key: nd
          Value: cdoe

  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref UdacityS3ReadOnlyEC2

  TestEC2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref ProfileWithRolesForOurApp
      InstanceType: t2.micro
      ImageId: ami-0ff8a91507f77f867
      Tags:
        - Key: Name
          Value: Test
        - Key: layer
          Value: web
      SubnetId: !ImportValue UdaPUBNETID